"""add_cash_company_percentage_to_cities

Revision ID: 0a7d4b502495
Revises: 04ef9d863238
Create Date: 2025-10-24 21:09:24.362486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a7d4b502495'
down_revision: Union[str, Sequence[str], None] = '04ef9d863238'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('cash_company_percentage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cities', 'cash_company_percentage')
    # ### end Alembic commands ###
