"""init

Revision ID: 47d580f2bd85
Revises: add_receipt_path_001
Create Date: 2025-11-09 23:49:32.292008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47d580f2bd85'
down_revision: Union[str, Sequence[str], None] = 'add_receipt_path_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Проверяем существование колонок перед изменением
    conn = op.get_bind()
    
    # Проверяем и изменяем attendance.check_in_time
    try:
        op.alter_column('attendance', 'check_in_time',
                   existing_type=postgresql.TIMESTAMP(timezone=True),
                   nullable=True,
                   existing_server_default=sa.text('now()'))
    except Exception:
        pass  # Колонка уже в нужном состоянии
    
    # Проверяем и изменяем attendance.is_penalty
    try:
        op.alter_column('attendance', 'is_penalty',
                   existing_type=sa.BOOLEAN(),
                   nullable=True,
                   existing_server_default=sa.text('false'))
    except Exception:
        pass  # Колонка уже в нужном состоянии
    
    # Проверяем и изменяем attendance.created_at
    try:
        op.alter_column('attendance', 'created_at',
                   existing_type=postgresql.TIMESTAMP(timezone=True),
                   nullable=True,
                   existing_server_default=sa.text('now()'))
    except Exception:
        pass  # Колонка уже в нужном состоянии
    
    # Проверяем существование колонки timezone перед добавлением
    result = conn.execute(sa.text("""
        SELECT column_name 
        FROM information_schema.columns 
        WHERE table_name='cities' AND column_name='timezone'
    """))
    if result.fetchone() is None:
        op.add_column('cities', sa.Column('timezone', sa.String(length=100), nullable=True))
    
    # Проверяем и изменяем penalties.amount
    try:
        op.alter_column('penalties', 'amount',
                   existing_type=sa.DOUBLE_PRECISION(precision=53),
                   nullable=True,
                   existing_server_default=sa.text('0'))
    except Exception:
        pass  # Колонка уже в нужном состоянии
    
    # Проверяем и изменяем penalties.created_at
    try:
        op.alter_column('penalties', 'created_at',
                   existing_type=postgresql.TIMESTAMP(timezone=True),
                   nullable=True,
                   existing_server_default=sa.text('now()'))
    except Exception:
        pass  # Колонка уже в нужном состоянии
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('penalties', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('penalties', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_column('cities', 'timezone')
    op.alter_column('attendance', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('attendance', 'is_penalty',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('attendance', 'check_in_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
