"""init

Revision ID: bea38e3e2a7c
Revises: c9d2f40186ce
Create Date: 2025-10-13 00:09:49.537619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bea38e3e2a7c'
down_revision: Union[str, Sequence[str], None] = 'c9d2f40186ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('orders', sa.Column('city_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'cities', ['city_id'], ['id'])
    op.drop_column('orders', 'city')
    op.add_column('users', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('city_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('full_name', sa.String(length=200), nullable=True))
    op.create_foreign_key(None, 'users', 'cities', ['city_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'city_id')
    op.drop_column('users', 'phone')
    op.add_column('orders', sa.Column('city', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'city_id')
    op.drop_table('cities')
    # ### end Alembic commands ###
