"""init

Revision ID: c9d2f40186ce
Revises: 19e7bf038884
Create Date: 2025-10-12 15:38:09.919355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9d2f40186ce'
down_revision: Union[str, Sequence[str], None] = '19e7bf038884'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('client_name', sa.String(length=200), nullable=True))
    op.add_column('orders', sa.Column('comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'comment')
    op.drop_column('orders', 'client_name')
    # ### end Alembic commands ###
