"""add_master_percentage_to_users

Revision ID: f7a99a334367
Revises: 0a7d4b502495
Create Date: 2025-10-25 19:24:00.023509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7a99a334367'
down_revision: Union[str, Sequence[str], None] = '0a7d4b502495'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('master_percentage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'master_percentage')
    # ### end Alembic commands ###
